version: "3.8"
services:
  nginx:
    image: nginx:1.24.0-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./server.crt:/etc/nginx/server.crt
      - ./server.key:/etc/nginx/server.key
      - ./frontend/dist:/etc/nginx/static
  app:
    image: amazoncorretto:17-alpine
    ports:
      - 8080:8080
    command: "java -Dspring.web.resources.static-locations=file:/etc/dist/ -jar /etc/app.jar"
    volumes:
      - ./backend.jar:/etc/app.jar
      - ./frontend/dist:/etc/dist
